apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-eks-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-eks-app
  template:
    metadata:
      labels:
        app: my-eks-app
    spec:
      containers:
      - name: my-container
        image: <ECR_URI>:latest
        ports:
        - containerPort: 3000
